// Code generated by cmd/gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file ze_api.h
 * @version v1.15-r1.15.31
 *
 */

package gozel

import (
	"unsafe"

	"github.com/fumiama/gozel/internal/zecall"
)

// ZE_GET_KERNEL_BINARY_EXP_NAME Get Kernel Binary Extension Name
const ZE_GET_KERNEL_BINARY_EXP_NAME = "ZE_extension_kernel_binary_exp"

// ZeKernelGetBinaryExpVersion (ze_kernel_get_binary_exp_version_t) Get Kernel Binary Extension Version(s)
type ZeKernelGetBinaryExpVersion uint32

const (
	ZE_KERNEL_GET_BINARY_EXP_VERSION_1_0          ZeKernelGetBinaryExpVersion = /* ZE_MAKE_VERSION( 1, 0 ) */ ((1 << 16) | (0 & 0x0000ffff)) // ZE_KERNEL_GET_BINARY_EXP_VERSION_1_0 version 1.0
	ZE_KERNEL_GET_BINARY_EXP_VERSION_CURRENT      ZeKernelGetBinaryExpVersion = /* ZE_MAKE_VERSION( 1, 0 ) */ ((1 << 16) | (0 & 0x0000ffff)) // ZE_KERNEL_GET_BINARY_EXP_VERSION_CURRENT latest known version
	ZE_KERNEL_GET_BINARY_EXP_VERSION_FORCE_UINT32 ZeKernelGetBinaryExpVersion = 0x7fffffff                                                   // ZE_KERNEL_GET_BINARY_EXP_VERSION_FORCE_UINT32 Value marking end of ZE_KERNEL_GET_BINARY_EXP_VERSION_* ENUMs

)

// ZeKernelGetBinaryExp Retrieves kernel binary program data (ISA GEN format).
// /
// / @details
// /     - A valid kernel handle must be created with ::zeKernelCreate.
// /     - Returns Intel Graphics Assembly (GEN ISA) format binary program data
// /       for kernel handle.
// /     - The application may call this function from simultaneous threads.
// /     - The implementation of this function must be thread-safe.
// /
// / @returns
// /     - ::ZE_RESULT_SUCCESS
// /     - ::ZE_RESULT_ERROR_UNINITIALIZED
// /     - ::ZE_RESULT_ERROR_DEVICE_LOST
// /     - ::ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY
// /     - ::ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY
// /     - ::ZE_RESULT_ERROR_INVALID_ARGUMENT
// /     - ::ZE_RESULT_ERROR_UNSUPPORTED_FEATURE
// /     - ::ZE_RESULT_ERROR_DEPENDENCY_UNAVAILABLE
// /     - ::ZE_RESULT_ERROR_INSUFFICIENT_PERMISSIONS
// /     - ::ZE_RESULT_ERROR_NOT_AVAILABLE
// /     - ::ZE_RESULT_ERROR_DEVICE_REQUIRES_RESET
// /     - ::ZE_RESULT_ERROR_DEVICE_IN_LOW_POWER_STATE
// /     - ::ZE_RESULT_ERROR_UNKNOWN
// /     - ::ZE_RESULT_ERROR_INVALID_NULL_HANDLE
// /         + `nullptr == hKernel`
// /     - ::ZE_RESULT_ERROR_INVALID_NULL_POINTER
// /         + `nullptr == pSize`
// /         + `nullptr == pKernelBinary`
func ZeKernelGetBinaryExp(
	hKernel ZeKernelHandle, // hKernel [in] Kernel handle.
	pSize *uintptr, // pSize [in,out] pointer to variable with size of GEN ISA binary.
	pKernelBinary *uint8, // pKernelBinary [in,out] pointer to storage area for GEN ISA binary function.
) (ZeResult, error) {
	return zecall.Call[ZeResult]("zeKernelGetBinaryExp", uintptr(hKernel), uintptr(unsafe.Pointer(pSize)), uintptr(unsafe.Pointer(pKernelBinary)))
}
