// Code generated by cmd/gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file ze_api.h
 * @version v1.15-r1.15.31
 *
 */

package gozel

import (
	"unsafe"
)

// ZE_SRGB_EXT_NAME sRGB Extension Name
const ZE_SRGB_EXT_NAME = "ZE_extension_srgb"

// ZeSrgbExtVersion (ze_srgb_ext_version_t) sRGB Extension Version(s)
type ZeSrgbExtVersion uintptr

const (
	ZE_SRGB_EXT_VERSION_1_0          ZeSrgbExtVersion = /* ZE_MAKE_VERSION( 1, 0 ) */ ((1 << 16) | (0 & 0x0000ffff)) // ZE_SRGB_EXT_VERSION_1_0 version 1.0
	ZE_SRGB_EXT_VERSION_CURRENT      ZeSrgbExtVersion = /* ZE_MAKE_VERSION( 1, 0 ) */ ((1 << 16) | (0 & 0x0000ffff)) // ZE_SRGB_EXT_VERSION_CURRENT latest known version
	ZE_SRGB_EXT_VERSION_FORCE_UINT32 ZeSrgbExtVersion = 0x7fffffff                                                   // ZE_SRGB_EXT_VERSION_FORCE_UINT32 Value marking end of ZE_SRGB_EXT_VERSION_* ENUMs

)

// ZeSrgbExtDesc (ze_srgb_ext_desc_t) sRGB image descriptor
// /
// / @details
// /     - This structure may be passed to ::zeImageCreate via the `pNext` member
// /       of ::ze_image_desc_t
// /     - Used for specifying that the image is in sRGB format.
type ZeSrgbExtDesc struct {
	Stype ZeStructureType // Stype [in] type of this structure
	Pnext unsafe.Pointer  // Pnext [in][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Srgb  ZeBool          // Srgb [in] Is sRGB.

}
