// Code generated by cmd/gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file ze_api.h
 * @version v1.15-r1.15.31
 *
 */

package gozel

import (
	"unsafe"
)

// ZE_DEVICE_MEMORY_PROPERTIES_EXT_NAME Device Memory Properties Extension Name
const ZE_DEVICE_MEMORY_PROPERTIES_EXT_NAME = "ZE_extension_device_memory_properties"

// ZeDeviceMemoryPropertiesExtVersion (ze_device_memory_properties_ext_version_t) Device Memory Properties Extension Version(s)
type ZeDeviceMemoryPropertiesExtVersion uintptr
const (
	ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_1_0 ZeDeviceMemoryPropertiesExtVersion = /* ZE_MAKE_VERSION( 1, 0 ) */((( 1 << 16 )|( 0 & 0x0000ffff)))	// ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_1_0 version 1.0
	ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_CURRENT ZeDeviceMemoryPropertiesExtVersion = /* ZE_MAKE_VERSION( 1, 0 ) */((( 1 << 16 )|( 0 & 0x0000ffff)))	// ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_CURRENT latest known version
	ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_FORCE_UINT32 ZeDeviceMemoryPropertiesExtVersion = 0x7fffffff	// ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_FORCE_UINT32 Value marking end of ZE_DEVICE_MEMORY_PROPERTIES_EXT_VERSION_* ENUMs

)

// ZeDeviceMemoryExtType (ze_device_memory_ext_type_t) Memory module types
type ZeDeviceMemoryExtType uintptr
const (
	ZE_DEVICE_MEMORY_EXT_TYPE_HBM ZeDeviceMemoryExtType = 0	// ZE_DEVICE_MEMORY_EXT_TYPE_HBM HBM memory
	ZE_DEVICE_MEMORY_EXT_TYPE_HBM2 ZeDeviceMemoryExtType = 1	// ZE_DEVICE_MEMORY_EXT_TYPE_HBM2 HBM2 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_DDR ZeDeviceMemoryExtType = 2	// ZE_DEVICE_MEMORY_EXT_TYPE_DDR DDR memory
	ZE_DEVICE_MEMORY_EXT_TYPE_DDR2 ZeDeviceMemoryExtType = 3	// ZE_DEVICE_MEMORY_EXT_TYPE_DDR2 DDR2 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_DDR3 ZeDeviceMemoryExtType = 4	// ZE_DEVICE_MEMORY_EXT_TYPE_DDR3 DDR3 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_DDR4 ZeDeviceMemoryExtType = 5	// ZE_DEVICE_MEMORY_EXT_TYPE_DDR4 DDR4 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_DDR5 ZeDeviceMemoryExtType = 6	// ZE_DEVICE_MEMORY_EXT_TYPE_DDR5 DDR5 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR ZeDeviceMemoryExtType = 7	// ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR LPDDR memory
	ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR3 ZeDeviceMemoryExtType = 8	// ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR3 LPDDR3 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR4 ZeDeviceMemoryExtType = 9	// ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR4 LPDDR4 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR5 ZeDeviceMemoryExtType = 10	// ZE_DEVICE_MEMORY_EXT_TYPE_LPDDR5 LPDDR5 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_SRAM ZeDeviceMemoryExtType = 11	// ZE_DEVICE_MEMORY_EXT_TYPE_SRAM SRAM memory
	ZE_DEVICE_MEMORY_EXT_TYPE_L1 ZeDeviceMemoryExtType = 12	// ZE_DEVICE_MEMORY_EXT_TYPE_L1 L1 cache
	ZE_DEVICE_MEMORY_EXT_TYPE_L3 ZeDeviceMemoryExtType = 13	// ZE_DEVICE_MEMORY_EXT_TYPE_L3 L3 cache
	ZE_DEVICE_MEMORY_EXT_TYPE_GRF ZeDeviceMemoryExtType = 14	// ZE_DEVICE_MEMORY_EXT_TYPE_GRF Execution unit register file
	ZE_DEVICE_MEMORY_EXT_TYPE_SLM ZeDeviceMemoryExtType = 15	// ZE_DEVICE_MEMORY_EXT_TYPE_SLM Execution unit shared local memory
	ZE_DEVICE_MEMORY_EXT_TYPE_GDDR4 ZeDeviceMemoryExtType = 16	// ZE_DEVICE_MEMORY_EXT_TYPE_GDDR4 GDDR4 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_GDDR5 ZeDeviceMemoryExtType = 17	// ZE_DEVICE_MEMORY_EXT_TYPE_GDDR5 GDDR5 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_GDDR5X ZeDeviceMemoryExtType = 18	// ZE_DEVICE_MEMORY_EXT_TYPE_GDDR5X GDDR5X memory
	ZE_DEVICE_MEMORY_EXT_TYPE_GDDR6 ZeDeviceMemoryExtType = 19	// ZE_DEVICE_MEMORY_EXT_TYPE_GDDR6 GDDR6 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_GDDR6X ZeDeviceMemoryExtType = 20	// ZE_DEVICE_MEMORY_EXT_TYPE_GDDR6X GDDR6X memory
	ZE_DEVICE_MEMORY_EXT_TYPE_GDDR7 ZeDeviceMemoryExtType = 21	// ZE_DEVICE_MEMORY_EXT_TYPE_GDDR7 GDDR7 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_HBM2E ZeDeviceMemoryExtType = 22	// ZE_DEVICE_MEMORY_EXT_TYPE_HBM2E HBM2E memory
	ZE_DEVICE_MEMORY_EXT_TYPE_HBM3 ZeDeviceMemoryExtType = 23	// ZE_DEVICE_MEMORY_EXT_TYPE_HBM3 HBM3 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_HBM3E ZeDeviceMemoryExtType = 24	// ZE_DEVICE_MEMORY_EXT_TYPE_HBM3E HBM3E memory
	ZE_DEVICE_MEMORY_EXT_TYPE_HBM4 ZeDeviceMemoryExtType = 25	// ZE_DEVICE_MEMORY_EXT_TYPE_HBM4 HBM4 memory
	ZE_DEVICE_MEMORY_EXT_TYPE_FORCE_UINT32 ZeDeviceMemoryExtType = 0x7fffffff	// ZE_DEVICE_MEMORY_EXT_TYPE_FORCE_UINT32 Value marking end of ZE_DEVICE_MEMORY_EXT_TYPE_* ENUMs

)

// ZeDeviceMemoryExtProperties (ze_device_memory_ext_properties_t) Memory properties
/// 
/// @details
///     - This structure may be returned from ::zeDeviceGetMemoryProperties via
///       the `pNext` member of ::ze_device_memory_properties_t
type ZeDeviceMemoryExtProperties struct {
	Stype ZeStructureType	// Stype [in] type of this structure
	Pnext unsafe.Pointer	// Pnext [in,out][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Type ZeDeviceMemoryExtType	// Type [out] The memory type
	Physicalsize uint64	// Physicalsize [out] Physical memory size in bytes. A value of 0 indicates that this property is not known. However, a call to ::zesMemoryGetState() will correctly return the total size of usable memory.
	Readbandwidth uint32	// Readbandwidth [out] Design bandwidth for reads
	Writebandwidth uint32	// Writebandwidth [out] Design bandwidth for writes
	Bandwidthunit ZeBandwidthUnit	// Bandwidthunit [out] bandwidth unit

}

