// Code generated by cmd/gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file zes_api.h
 * @version v1.15-r1.15.31
 *
 */

package gozel

import (
	"unsafe"
)

// ZES_MEMORY_BANDWIDTH_COUNTER_BITS_EXP_PROPERTIES_NAME Memory Bandwidth Counter Valid Bits Extension Name
const ZES_MEMORY_BANDWIDTH_COUNTER_BITS_EXP_PROPERTIES_NAME = "ZES_extension_mem_bandwidth_counter_bits_properties"

// ZesMemBandwidthCounterBitsExpVersion (zes_mem_bandwidth_counter_bits_exp_version_t) Memory Bandwidth Counter Valid Bits Extension Version(s)
type ZesMemBandwidthCounterBitsExpVersion uintptr

const (
	ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_1_0          ZesMemBandwidthCounterBitsExpVersion = /* ZE_MAKE_VERSION( 1, 0 ) */ ((1 << 16) | (0 & 0x0000ffff)) // ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_1_0 version 1.0
	ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_CURRENT      ZesMemBandwidthCounterBitsExpVersion = /* ZE_MAKE_VERSION( 1, 0 ) */ ((1 << 16) | (0 & 0x0000ffff)) // ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_CURRENT latest known version
	ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_FORCE_UINT32 ZesMemBandwidthCounterBitsExpVersion = 0x7fffffff                                                   // ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_FORCE_UINT32 Value marking end of ZES_MEM_BANDWIDTH_COUNTER_BITS_EXP_VERSION_* ENUMs

)

// ZesMemBandwidthCounterBitsExpProperties (zes_mem_bandwidth_counter_bits_exp_properties_t) Extension properties for reporting valid bit count for memory
// /        bandwidth counter value
// /
// / @details
// /     - Number of valid read and write counter bits of memory bandwidth
// /     - This structure may be returned from ::zesMemoryGetProperties via the
// /       `pNext` member of ::zes_mem_properties_t.
// /     - Used for denoting number of valid bits in the counter value returned
// /       in ::zes_mem_bandwidth_t.
type ZesMemBandwidthCounterBitsExpProperties struct {
	Stype          ZesStructureType // Stype [in] type of this structure
	Pnext          unsafe.Pointer   // Pnext [in,out][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Validbitscount uint32           // Validbitscount [out] Returns the number of valid bits in the counter values

}
