// Code generated by cmd/gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file ze_api.h
 * @version v1.15-r1.15.31
 *
 */

package core

import (
	"unsafe"
)

// ZE_BANDWIDTH_PROPERTIES_EXP_NAME Bandwidth Extension Name
const ZE_BANDWIDTH_PROPERTIES_EXP_NAME = "ZE_experimental_bandwidth_properties"

// ZeBandwidthPropertiesExpVersion (ze_bandwidth_properties_exp_version_t) Bandwidth Extension Version(s)
type ZeBandwidthPropertiesExpVersion uintptr
const (
	ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_1_0 ZeBandwidthPropertiesExpVersion = /* ZE_MAKE_VERSION( 1, 0 ) */((( 1 << 16 )|( 0 & 0x0000ffff)))	// ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_1_0 version 1.0
	ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_CURRENT ZeBandwidthPropertiesExpVersion = /* ZE_MAKE_VERSION( 1, 0 ) */((( 1 << 16 )|( 0 & 0x0000ffff)))	// ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_CURRENT latest known version
	ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_FORCE_UINT32 ZeBandwidthPropertiesExpVersion = 0x7fffffff	// ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_FORCE_UINT32 Value marking end of ZE_BANDWIDTH_PROPERTIES_EXP_VERSION_* ENUMs

)

// ZeDeviceP2pBandwidthExpProperties (ze_device_p2p_bandwidth_exp_properties_t) P2P Bandwidth Properties
/// 
/// @details
///     - This structure may be passed to ::zeDeviceGetP2PProperties by having
///       the pNext member of ::ze_device_p2p_properties_t point at this struct.
type ZeDeviceP2pBandwidthExpProperties struct {
	Stype ZeStructureType	// Stype [in] type of this structure
	Pnext unsafe.Pointer	// Pnext [in,out][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Logicalbandwidth uint32	// Logicalbandwidth [out] total logical design bandwidth for all links connecting the two devices
	Physicalbandwidth uint32	// Physicalbandwidth [out] total physical design bandwidth for all links connecting the two devices
	Bandwidthunit ZeBandwidthUnit	// Bandwidthunit [out] bandwidth unit
	Logicallatency uint32	// Logicallatency [out] average logical design latency for all links connecting the two devices
	Physicallatency uint32	// Physicallatency [out] average physical design latency for all links connecting the two devices
	Latencyunit ZeLatencyUnit	// Latencyunit [out] latency unit

}

// ZeCopyBandwidthExpProperties (ze_copy_bandwidth_exp_properties_t) Copy Bandwidth Properties
/// 
/// @details
///     - This structure may be passed to
///       ::zeDeviceGetCommandQueueGroupProperties by having the pNext member of
///       ::ze_command_queue_group_properties_t point at this struct.
///     - [DEPRECATED]
type ZeCopyBandwidthExpProperties struct {
	Stype ZeStructureType	// Stype [in] type of this structure
	Pnext unsafe.Pointer	// Pnext [in,out][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Copybandwidth uint32	// Copybandwidth [out] design bandwidth supported by this engine type for copy operations
	Copybandwidthunit ZeBandwidthUnit	// Copybandwidthunit [out] copy bandwidth unit

}

