// Code generated by gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file ze_api.h
 * @version v1.15-r1.15.31
 *
 */

package core

// ZE_MAKE_VERSION Generates generic 'oneAPI' API versions
func ZE_MAKE_VERSION[T ~int | ~uint64 | ~uintptr](_major T, _minor T) T {
	return (( _major << 16 )|( _minor & 0x0000ffff))
}

// ZE_MAJOR_VERSION Extracts 'oneAPI' API major version
func ZE_MAJOR_VERSION[T ~int | ~uint64 | ~uintptr](_ver T) T {
	return ( _ver >> 16 )
}

// ZE_MINOR_VERSION Extracts 'oneAPI' API minor version
func ZE_MINOR_VERSION[T ~int | ~uint64 | ~uintptr](_ver T) T {
	return ( _ver & 0x0000ffff )
}

// ZeBool (ze_bool_t) compiler-independent type
type ZeBool uint8

// ZeDriverHandle (ze_driver_handle_t) Handle of a driver instance
type ZeDriverHandle uintptr

// ZeDeviceHandle (ze_device_handle_t) Handle of driver's device object
type ZeDeviceHandle uintptr

// ZeContextHandle (ze_context_handle_t) Handle of driver's context object
type ZeContextHandle uintptr

// ZeCommandQueueHandle (ze_command_queue_handle_t) Handle of driver's command queue object
type ZeCommandQueueHandle uintptr

// ZeCommandListHandle (ze_command_list_handle_t) Handle of driver's command list object
type ZeCommandListHandle uintptr

// ZeFenceHandle (ze_fence_handle_t) Handle of driver's fence object
type ZeFenceHandle uintptr

// ZeEventPoolHandle (ze_event_pool_handle_t) Handle of driver's event pool object
type ZeEventPoolHandle uintptr

// ZeEventHandle (ze_event_handle_t) Handle of driver's event object
type ZeEventHandle uintptr

// ZeImageHandle (ze_image_handle_t) Handle of driver's image object
type ZeImageHandle uintptr

// ZeModuleHandle (ze_module_handle_t) Handle of driver's module object
type ZeModuleHandle uintptr

// ZeModuleBuildLogHandle (ze_module_build_log_handle_t) Handle of module's build log object
type ZeModuleBuildLogHandle uintptr

// ZeKernelHandle (ze_kernel_handle_t) Handle of driver's kernel object
type ZeKernelHandle uintptr

// ZeSamplerHandle (ze_sampler_handle_t) Handle of driver's sampler object
type ZeSamplerHandle uintptr

// ZePhysicalMemHandle (ze_physical_mem_handle_t) Handle of physical memory object
type ZePhysicalMemHandle uintptr

// ZeFabricVertexHandle (ze_fabric_vertex_handle_t) Handle of driver's fabric vertex object
type ZeFabricVertexHandle uintptr

// ZeFabricEdgeHandle (ze_fabric_edge_handle_t) Handle of driver's fabric edge object
type ZeFabricEdgeHandle uintptr

// ZE_MAX_IPC_HANDLE_SIZE Maximum IPC handle size
const ZE_MAX_IPC_HANDLE_SIZE = 64

