// Code generated by cmd/gen. DO NOT EDIT.

/*
 *
 * Copyright (C) 2019-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 * @file ze_api.h
 * @version v1.15-r1.15.31
 *
 */

package core

import (
	"unsafe"
)

// ZE_RAYTRACING_EXT_NAME Raytracing Extension Name
const ZE_RAYTRACING_EXT_NAME = "ZE_extension_raytracing"

// ZeRaytracingExtVersion (ze_raytracing_ext_version_t) Raytracing Extension Version(s)
type ZeRaytracingExtVersion uintptr
const (
	ZE_RAYTRACING_EXT_VERSION_1_0 ZeRaytracingExtVersion = /* ZE_MAKE_VERSION( 1, 0 ) */((( 1 << 16 )|( 0 & 0x0000ffff)))	// ZE_RAYTRACING_EXT_VERSION_1_0 version 1.0
	ZE_RAYTRACING_EXT_VERSION_CURRENT ZeRaytracingExtVersion = /* ZE_MAKE_VERSION( 1, 0 ) */((( 1 << 16 )|( 0 & 0x0000ffff)))	// ZE_RAYTRACING_EXT_VERSION_CURRENT latest known version
	ZE_RAYTRACING_EXT_VERSION_FORCE_UINT32 ZeRaytracingExtVersion = 0x7fffffff	// ZE_RAYTRACING_EXT_VERSION_FORCE_UINT32 Value marking end of ZE_RAYTRACING_EXT_VERSION_* ENUMs

)

// ZeDeviceRaytracingExtFlags (ze_device_raytracing_ext_flags_t) Supported raytracing capability flags
type ZeDeviceRaytracingExtFlags uint32
const (
	ZE_DEVICE_RAYTRACING_EXT_FLAG_RAYQUERY ZeDeviceRaytracingExtFlags = /* ZE_BIT(0) */(( 1 << 0 ))	// ZE_DEVICE_RAYTRACING_EXT_FLAG_RAYQUERY Supports rayquery
	ZE_DEVICE_RAYTRACING_EXT_FLAG_FORCE_UINT32 ZeDeviceRaytracingExtFlags = 0x7fffffff	// ZE_DEVICE_RAYTRACING_EXT_FLAG_FORCE_UINT32 Value marking end of ZE_DEVICE_RAYTRACING_EXT_FLAG_* ENUMs

)

// ZeDeviceRaytracingExtProperties (ze_device_raytracing_ext_properties_t) Raytracing properties queried using ::zeDeviceGetModuleProperties
/// 
/// @details
///     - This structure may be returned from ::zeDeviceGetModuleProperties, via
///       the `pNext` member of ::ze_device_module_properties_t.
type ZeDeviceRaytracingExtProperties struct {
	Stype ZeStructureType	// Stype [in] type of this structure
	Pnext unsafe.Pointer	// Pnext [in,out][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Flags ZeDeviceRaytracingExtFlags	// Flags [out] 0 or a valid combination of ::ze_device_raytracing_ext_flags_t
	Maxbvhlevels uint32	// Maxbvhlevels [out] Maximum number of BVH levels supported

}

// ZeRaytracingMemAllocExtFlags (ze_raytracing_mem_alloc_ext_flags_t) Supported raytracing memory allocation flags
type ZeRaytracingMemAllocExtFlags uint32
const (
	ZE_RAYTRACING_MEM_ALLOC_EXT_FLAG_TBD ZeRaytracingMemAllocExtFlags = /* ZE_BIT(0) */(( 1 << 0 ))	// ZE_RAYTRACING_MEM_ALLOC_EXT_FLAG_TBD reserved for future use
	ZE_RAYTRACING_MEM_ALLOC_EXT_FLAG_FORCE_UINT32 ZeRaytracingMemAllocExtFlags = 0x7fffffff	// ZE_RAYTRACING_MEM_ALLOC_EXT_FLAG_FORCE_UINT32 Value marking end of ZE_RAYTRACING_MEM_ALLOC_EXT_FLAG_* ENUMs

)

// ZeRaytracingMemAllocExtDesc (ze_raytracing_mem_alloc_ext_desc_t) Raytracing memory allocation descriptor
/// 
/// @details
///     - This structure must be passed to ::zeMemAllocShared or
///       ::zeMemAllocDevice, via the `pNext` member of
///       ::ze_device_mem_alloc_desc_t, for any memory allocation that is to be
///       accessed by raytracing fixed-function of the device.
type ZeRaytracingMemAllocExtDesc struct {
	Stype ZeStructureType	// Stype [in] type of this structure
	Pnext unsafe.Pointer	// Pnext [in][optional] must be null or a pointer to an extension-specific structure (i.e. contains stype and pNext).
	Flags ZeRaytracingMemAllocExtFlags	// Flags [in] flags specifying additional allocation controls. must be 0 (default) or a valid combination of ::ze_raytracing_mem_alloc_ext_flag_t; default behavior may use implicit driver-based heuristics.

}

